language: python
python:
  - 3.4
  - 3.3
  - 3.2
  - 2.7
  - 2.6
install:
  - pip install -r dev_requirements.txt
  - python setup.py develop
script:
  - python -m unittest discover tests
notifications:
  email:
      - robert.kern+travis-ci@gmail.com
